name: GoLang CI Coverage 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      
      - name: Github Action for testing the code
        run: |
          go clean -testcache
          go test ./...

      - name: Github Action to retrieve coverage percentage
        id: total-coverage
        run: |
          coverage=$(go tool cover -func=coverage.out | grep total | awk '{print $3}')
            if [ "$coverage" -lt "$MIN_COVERAGE_REQUIRED" ]; then
            echo "Coverage is too low: $coverage%"
            exit 1
          fi

